In [52]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [53]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotions'])

In [54]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [55]:
emotions = df['emotions'].unique()

In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
le = LabelEncoder()

In [58]:
df['emotions'] =le.fit_transform(df['emotions'])

In [59]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]

In [60]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [61]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]

In [62]:
import string
# translator = str.maketrans('', '', string.punctuation)
marks = string.punctuation

In [63]:
def remove_punc(text):
    for char in marks:
        text= text.replace(char,'')
    return text

In [64]:
df['text']=df['text'].apply(remove_punc)

In [65]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]

In [66]:
import string
def remove_punc_ap(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [67]:
df['text']= df['text'].apply(remove_punc_ap)

In [68]:
def reomve_number(txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new+=i
    return new

In [69]:
df['text']=df['text'].apply(reomve_number)

In [70]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [71]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (3.10.3)
Requirement already satisfied: defusedxml in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.9.10)
Requirement already satisfied: tqdm in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in C:\Users\subha\AppData\Roaming\Python\Python314\site-packages (from tqdm->nltk) (0.4.6)

In [72]:
import nltk

In [73]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [74]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\subha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\subha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [75]:
stop_words = set(stopwords.words('english'))

In [76]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [77]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [78]:
def remove_stop(txt):
    words = word_tokenize(txt)
    cleaned=[]
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return  ' '.join(cleaned)

In [79]:
df['text']= df['text'].apply(remove_stop)

In [81]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'