In [2]:
import pandas as pd

In [3]:
df =pd.read_csv("IMDB Dataset.csv")

In [4]:
import re

In [5]:
def removal_html_tag(text):
    pattern =re.compile('<.*?>')
    return pattern.sub(r'',text)

In [6]:
text = '<p>This is the second paragraph, separated by a line.</p>'

print(removal_html_tag(text))

This is the second paragraph, separated by a line.

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [14]:
df['review']=df['review'].apply(removal_html_tag)

In [15]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [18]:
import string
# translator = str.maketrans('', '', string.punctuation)
marks = string.punctuation

In [19]:
marks

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
def remove_punc(text):
    for char in marks:
        text= text.replace(char,'')
    return text

In [27]:
df['review']=df['review'].apply(remove_punc)

In [22]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',marks))

In [28]:
df['review']=df['review'].apply(remove_punc1)

In [29]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str